import { ApplicationConfig, provideBrowserGlobalErrorListeners, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideCharts, withDefaultRegisterables } from 'ng2-charts';
import { provideLucideIcons } from '@lucide/angular';
import {
  LucideLayoutDashboard,
  LucideBuilding2,
  LucideDoorOpen,
  LucideCpu,
  LucideZap,
  LucideCalendarClock,
  LucideBellRing,
  LucideUser,
  LucideSettings,
  LucideChevronLeft,
  LucideChevronRight,
  LucideLogOut,
  LucideBell,
  LucideSearch,
  LucidePlus,
  LucideX,
  LucideCheckCircle,
  LucideAlertTriangle,
  LucideInfo,
  LucideMoon,
  LucideSun,
  LucideWifi,
  LucideWifiOff,
  LucideThermometer,
  LucideActivity,
  LucideBarChart2,
  LucideClock,
  LucideHome,
  LucideLamp,
  LucideTv,
  LucideWind,
  LucideWashingMachine,
  LucideCoffee,
  LucideRefrigerator,
} from '@lucide/angular';

import { routes } from './app.routes';
import { authInterceptor } from './servicios/auth.interceptor';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    provideCharts(withDefaultRegisterables()),
    provideLucideIcons(
      LucideLayoutDashboard,
      LucideBuilding2,
      LucideDoorOpen,
      LucideCpu,
      LucideZap,
      LucideCalendarClock,
      LucideBellRing,
      LucideUser,
      LucideSettings,
      LucideChevronLeft,
      LucideChevronRight,
      LucideLogOut,
      LucideBell,
      LucideSearch,
      LucidePlus,
      LucideX,
      LucideCheckCircle,
      LucideAlertTriangle,
      LucideInfo,
      LucideMoon,
      LucideSun,
      LucideWifi,
      LucideWifiOff,
      LucideThermometer,
      LucideActivity,
      LucideBarChart2,
      LucideClock,
      LucideHome,
      LucideLamp,
      LucideTv,
      LucideWind,
      LucideWashingMachine,
      LucideCoffee,
      LucideRefrigerator
    ),
  ]
};
